name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      # - name: Run tests
      #   run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build the application
        run: yarn build

      # - name: Deploy to server
      #   env:
      #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # Добавьте ваш ключ деплоя в Secrets
      #   run: |
      #     # Команды для деплоя (например, scp или rsync)
      #     ssh -i $DEPLOY_KEY user@yourserver.com "cd /path/to/app && git pull && yarn install && yarn start"
